[WIP] Add /consider-arrangement proxy endpoint
nucypher/nucypher pull request #2803
Opened 2021-09-29 13:58 UTC by piotr-roslaniec

**Type of PR:**
- [ ] Bugfix
- [x] Feature
- [ ] Documentation
- [ ] Other

**Required reviews:** 
- [ ] 1
- [x] 2
- [ ] 3

**What this does:**
- Adds `/consider-arrangement` Porter endpoint in order to enable `nucypher-ts` in the browser.

**Issues fixed/closed:**
- #2763

**Notes for reviewers:**
- This PR is subject to change per discussion in #2763. I'm putting it out here in order to track this issue and reference it in `nucypher-ts` docs - Early `nucypher-ts` users could find it useful.

2021-09-29 17:38 UTC, KPrasch commented on nucypher/control/controllers.py
> +            request_headers = {header.upper(): value for (header, value) in request_headers.items()}
Heh, the headers must begin with an uppercase letter?

Also, just a style comment, parenthesis are not needed here:
```suggestion
            request_headers = {header.upper(): value for header, value in request_headers.items()}
```

2021-09-29 17:38 UTC, KPrasch commented on nucypher/control/controllers.py
> +                request_body = {"data": bytes(request_data)}
If the request header specifies a content type of bytes, isn't the body already bytes?  Is this just a matter of getting the bytes into a dictionary for consumption?

2021-09-29 17:38 UTC, KPrasch commented on nucypher/control/controllers.py
> +                request_body['proxy_destination'] = request_headers['X-PROXY-DESTINATION']
Hmm it's unclear what is meant here, is `proxy_destination` an alias for `X_PROXY_DESTINATION`?

2021-09-29 17:38 UTC, KPrasch commented on nucypher/utilities/porter/porter.py
> +            raise RuntimeError(response.content)
Is `RuntimeError` used to handle other 500s too?

2021-09-29 19:45 UTC, derekpierre commented
See comment here - https://github.com/nucypher/nucypher/issues/2763#issuecomment-930489105.

2021-09-30 12:46 UTC, derekpierre requested changes
Just formalizing that this PR should be closed based on the result of discussions documented here - https://github.com/nucypher/nucypher/issues/2763#issuecomment-930489105.

2021-09-30 16:22 UTC, piotr-roslaniec commented
Closing without merging since these changes are superfluous per discussion in #2763.

2021-09-30 16:22 UTC, closed without merging