tDec global keygen script
nucypher/nucypher pull request #2951
Opened 2022-06-25 21:27 UTC by KPrasch

Hackathon

2022-07-04 17:42 UTC, cygnusv requested changes

2022-07-04 17:42 UTC, cygnusv commented on scripts/tdec/keygen.py
> +                     duration=3600*365)
I think this policy only works for 365 hours (15 days), not a year

```suggestion
                     duration=86400*365)
```

2022-07-06 14:00 UTC, derekpierre commented
Rebase over the latest `development` for the `cli` build tests to pass - the issue is the probation period needing to be extended which it was in a recent PR.

2022-07-06 17:37 UTC, arjunhassard commented on scripts/tdec/network_config.json
> +    "bob_encrypting_secret": "073e656ca21122485b3a2b4102f668c70436d91bdf9a140f5ea3fb45dc33fa4f"
Just to be clear. Forthcoming versions will have gatekeeping conditions, right now the conditions are 'there are no conditions', so anyone can decrypt (and anyone can encrypt to the policy too!). And these private keys are basically there for the entire network – so everyone uses the same keys and they're not really private in any sense. Is this secure, even when there is strict conditionality?

2022-07-06 17:37 UTC, arjunhassard commented on scripts/tdec/keygen.py
> +    # TODO: store Alice's secret?
What power does Alice's secret give her in perpetuity? Does it mean she can never actually be revoked from the policy, even when she consents to be revoked – either as part of an interactive atomized NFT selling+signing function, or conditionally/non-interactively (if someone pays this amount, revoke me) – plus an honest majority of Ursulas that execute it?

2022-07-06 22:35 UTC, KPrasch commented
Obsoleted by https://github.com/nucypher/network-keys

2022-07-06 22:35 UTC, closed without merging