[WIP] Simplify simplified tooling - remove return of TDR when encrypting
nucypher/nucypher pull request #3179
Opened 2023-07-09 14:45 UTC by derekpierre

**Type of PR:**
- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [X] Other

**Required reviews:** 
- [ ] 1
- [X] 2
- [ ] 3

**What this does:**
Removes the ThresholdDecryptionRequest being returned by Enrico.

**Issues fixed/closed:**
Based over #3174 .

**Why it's needed:**
Threshold Decryption Requests should not be returned by Enrico. It is really a decryption object that Bob populates because it contains `variant` and the `context` dictionary (think Bob signing to prove ownership of a wallet). Therefore, the TDR should only be constructed by Bob and not Enrico.

**Notes for reviewers:**
> What should reviewers focus on? 
> Is there a particular commit/function/section of your PR that requires more attention from reviewers?

2023-07-12 08:36 UTC, piotr-roslaniec commented on nucypher/characters/chaotic.py
> +            #  provided in constructor
Possibly material for `ferveo` issue

2023-07-12 08:37 UTC, piotr-roslaniec approved these changes

2023-07-12 18:55 UTC, manumonti approved these changes
LGTM! ✌️

2023-07-12 18:56 UTC, derekpierre commented on nucypher/characters/chaotic.py
> +            # TODO this list should have to be passed again (either make `verify` static or use list
```suggestion
            # TODO this list should not have to be passed again (either make `verify` static or use list
```

2023-07-12 18:57 UTC, derekpierre commented on nucypher/characters/chaotic.py
> +            #  provided in constructor
Indeed. This list is passed in the constructor, and then again in the `verify` function - which is redundant.

2023-07-12 19:14 UTC, KPrasch requested changes
LGTM - just need to fix the linting errors, and merge the dependency!

2023-07-13 01:25 UTC, KPrasch approved these changes

2023-07-13 01:26 UTC, KPrasch commented
I fixed the linting issues in PR #3182

2023-07-13 01:26 UTC, merged

2023-07-13 12:11 UTC, derekpierre commented
> I fixed the linting issues in PR #3182

Thanks 🙏